### PR TITLE
SM-686: Send location every Configurable X seconds, as low as 1/sec

### PR DESCRIPTION
**Pull request by zakharenkodmytro**
- added LocationFrequencySecs setting

### CODE REVIEW

**Review by JamesReate — APPROVED** [review]

**Comment by zakharenkodmytro** [comment]
@mateuszpohl , could you please take a look? I want to ensure this won't break the Macaron config on 0.9.1.

**Review by mateuszpohl — APPROVED** [review]
I've tested protobuf encoded file with this field included in current Macaron FW - no issues.

One question though: shouldn't this new field have some default value? Like e.g. `min_voltage_obd_loggers` (13.3V)?

**Comment by zakharenkodmytro** [comment]
> I've tested protobuf encoded file with this field included in current Macaron FW - no issues.
> 
> One question though: shouldn't this new field have some default value? Like e.g. `min_voltage_obd_loggers` (13.3V)?
Thanks for testing, 
I think the default should be 0.
The reason behind it is that we want to send locations so frequently only for some particular customers, in case if location_frequency_secs == 0, the location data will be sent as before(every 20 sec) with all the other payload. @JamesReate any thoughts?

**Comment by JamesReate** [comment]
I would have the default be 20 seconds, (what we currently do).

**Comment by JamesReate** [comment]
if set to 0, it could mean to use the device default, although some could interpret it to not send location at all 🤷

**Pull request merged**
